obj-y  = labx_nios2_devicetree.o

obj-y += nios2_pic_cpu.o
obj-$(CONFIG_FDT) += ../device_tree.o

obj-$(CONFIG_FDT_GENERIC) += fdt_generic.o
obj-$(CONFIG_FDT_GENERIC) += fdt_generic_util.o
obj-$(CONFIG_FDT_GENERIC) += fdt_generic_devices.o

obj-y := $(addprefix ../,$(obj-y))
